spring:
  profiles:
    active: dev, security
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org.hibernate.SQL: debug

spring.main.allow-bean-definition-overriding: true


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

