spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/modugarden
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Redis
  redis:
    host: localhost
    port: 6379 # 기본 port 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true