spring:
  profiles:
    active: local, security
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

logging.level:
  org.hibernate.SQL: debug

spring.main.allow-bean-definition-overriding: true


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

